[View in Colaboratory](https://colab.research.google.com/github/raviudal/Jupyter-Notebooks/blob/master/PythonDataScienceHandbook_by_jakevdp_Basics_of_NumPy.ipynb)

## Python Data Science Handbook by Jake VanderPlas <br> https://jakevdp.github.io/PythonDataScienceHandbook

### The Basics of NumPy Arrays  https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html

##### Numpy array attributes.
We will start by defineing the random method

In [0]:
import numpy as np
n1 = np.random.randint(10, size=6) # for defining one dimentional array od size 6 and values utpo 0 to 10
n2 = np.random.randint(10, size=(3,4)) # for defining two dimentional array od size 6 X 3 and values utpo 0 to 10
n3 = np.random.randint(10, size=(6,3,3)) # for defining two dimentional array od size 6 X 3 X 3 and values utpo 0 to 10

In [36]:
# Now each defined array will have some attributes like : ndim, shape, size
print('Every numpy array have some attributes, few of them are there;')
print('n2 ndim attr :',n2.ndim)
print('n2 shape attr :',n2.shape)
print('n2 size attr :',n2.size)
print('n2 size dtype (Date type) :',n2.dtype)

Every numpy array have some attributes, few of them are there;
n2 ndim attr : 2
n2 shape attr : (3, 3)
n2 size attr : 9
n2 size dtype (Date type) : int64


##### Array Indexing: Accessing Single Elements


In [26]:
# For accesing any array element we have to specify the index number of that array
print('Array\t\t\t\t:',n1)
print('Fifth element of the array\t: ',n1[4])
print('Last element of the array\t: ',n1[-1],',',n1[-2] )


Array				: [9 6 0 4 2 5]
Fifth element of the array	:  2
Last element of the array	:  5 , 2


In [37]:
# For selecting from the 2-D array
print(n2)
print('selecting specific element: ',n2[0,1])

# Or we can change the specific element
n2[0,1] = 9
print(n2)

[[7 8 9]
 [9 0 4]
 [6 1 4]]
selecting specific element:  8
[[7 9 9]
 [9 0 4]
 [6 1 4]]


##### Array Slicing: Accessing Subarrays

In [44]:
## Proper syntax for slicing is  ->      x[start:stop:step]
print(n1)
print('slice upto 3rd element:', n1[:3])
print('slice 2nd to 5th element:', n1[1:5])
print('slice upto 3rd element:', n1[:3])
print('slice and step of 2 elements:', n1[::2])


[1 3 7 7 1 1]
slice upto 3rd element: [1 3 7]
slice 2nd to 5th element: [3 7 7 1]
slice upto 3rd element: [1 3 7]
slice and step to 2: [1 7 1]


##### Multi-dimensional subarrays

In [51]:
print(n2)
print('\n two rows, three columns\n', n2[:2][:3])
print('\n # all rows, every other column\n', n2[:3][::2])

[[1 6 5 4]
 [3 3 6 8]
 [8 5 3 6]]

 two rows, three columns
 [[1 6 5 4]
 [3 3 6 8]]

 # all rows, every other column
 [[1 6 5 4]
 [8 5 3 6]]


##### Subarrays as no-copy views
One important–and extremely useful–thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies. 

In [58]:
print(n2)
n2_sub = n2[:2,:2]
print('\nNew Sub array is: \n', n2_sub)
n2_sub[0,0] = 99
print('\nNew Sub array is: \n', n2)

[[2 8 7 9]
 [5 2 5 0]
 [9 5 5 6]]

New Sub array is: 
 [[2 8]
 [5 2]]

New Sub array is: 
 [[99  8  7  9]
 [ 5  2  5  0]
 [ 9  5  5  6]]


In [61]:
#  Creating copies of arrays
n2_sub_copy = n2[:2,:2].copy()
print('Copied array: \n', n2_sub_copy)
n2_sub_copy[0,0] = 40
print('\nModified Copied array: \n', n2_sub_copy)
print('\nOriginal array :\n', n2)


Copied array: 
 [[99  8]
 [ 5  2]]

Modified Copied array: 
 [[40  8]
 [ 5  2]]

Original array :
 [[99  8  7  9]
 [ 5  2  5  0]
 [ 9  5  5  6]]


##### Reshaping of Arrays
Reshaping can be done by using the reshaping method of the np array

In [62]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### Array Concatenation and Splitting
Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines `np.concatenate`,` np.vstack`, and `np.hstack`. `np.concatenate` takes a tuple or list of arrays as its first argument

In [69]:
## Concatinating two arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(np.concatenate([x, y]))

# Concatinating more than 2 arrays
z = [99, 99, 99]
print('\n')
print(np.concatenate([x, y, z]))

[1 2 3 3 2 1]


[ 1  2  3  3  2  1 99 99 99]


In [79]:
## It can also be used for two-dimensional arrays:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

np.concatenate([grid, grid] ,axis=1) # axis =0 can be used for vertical concatenation

## But we can use vstack for verical stacking and hstack for horizontal stacking

print('Veritcal stacking:\n',np.vstack([grid, grid]))
print('\nHorizontal stacking:\n',np.hstack([grid, grid]))

Veritcal stacking:
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

Horizontal stacking:
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [84]:
## Splitting of arrays
x = np.arange(10)
x1,x2,x3 = np.split(x,[3,5])
print(x1,',',x2,',',x3)

# Split takes the list of index on wich we want the spliting



[0 1 2] , [3 4] , [5 6 7 8 9]


### [Computation on NumPy Arrays: Universal Functions](https://jakevdp.github.io/PythonDataScienceHandbook/02.03-computation-on-arrays-ufuncs.html)
Generally python functions are slow due to its interpretable language property.<br>
So if we want ot perform operations on the numpy array then we must perform operation using UFuncs which is nothing but simply scalar operation on the arrays.

In [92]:
# Suppose we want to calculate the reciprocal of the array then we may right below function (which is show while executing)
x = np.arange(10000)

def recirocal(ar):
  temp = np.empty(len(ar))
  for i in range(len(ar)):
    temp[i] = 1/ar[1]
  return temp

%timeit recirocal(x)
   
# Below is the time taken by the python loop

100 loops, best of 3: 2.69 ms per loop


In [93]:
# But if we are using the UFuncs of numpy then

%timeit 1/x

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


The slowest run took 23.61 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 27.1 µs per loop


##### Exploring NumPy's UFuncs

In [0]:
# Array arithmetic
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

In [99]:
# Absolute value
x = np.array([-2, -1, 0, 1, 2])
%timeit abs(x)
%timeit np.abs(x)
# x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
# np.abs(x)

The slowest run took 38.83 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 501 ns per loop
The slowest run took 22.92 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 470 ns per loop


In [100]:
# Trigonometric functions

theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))


# Inverse Trigonometric functions are also available:

x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [0]:
# Exponents and logarithms

x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

# Inverse of the exponentials

x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))


##### Advanced Ufunc Features

In [102]:
# **Specifying output**
# For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored. Rather than creating a 
# temporary array, this can be used to write computation results directly to the memory location where you'd like them to be. For all ufuncs, this can be done 
# using the out argument of the function:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)



# **Aggregates**
# For binary ufuncs, there are some interesting aggregates that can be computed directly from the object. For example, if we'd like to reduce an array with a 
# particular operation, we can use the reduce method of any ufunc. A reduce repeatedly applies a given operation to the elements of an array until only a single 
# result remains.
x = np.arange(1, 6)
print('Adding all the values of the array using UFuncs: ',np.add.reduce(x))
# Simmilarly
print('Adding all the values of the array using UFuncs: ',np.multiply.reduce(x))


# If we'd like to store all the intermediate results of the computation, we can instead use accumulate:
print('Accumulation of the array with stored result: ',np.add.accumulate(x))

[ 0. 10. 20. 30. 40.]
Adding all the values of the array using UFuncs 15
Adding all the values of the array using UFuncs 120
Accumulation of the array with stored result:  [ 1  3  6 10 15]


### [Aggregations: Min, Max, and Everything In Between](https://jakevdp.github.io/PythonDataScienceHandbook/02.04-computation-on-arrays-aggregates.html)

In [109]:
# Summing

x = np.random.random(100)

print('np.sum',np.sum(x))
print('np.min',np.min(x)) 
print('np.max',np.max(x))
print('\n')

# Multi dimensional aggregates
x = x.reshape(10,10)

print('np.sum',np.sum(x))

np.sum 43.39128374967406
np.min 0.006655743945536474
np.max 0.9983456789086161


np.sum 43.39128374967406
